const { spawn, execSync } = require('child_process');
const path = require('path');
const shell = require('shelljs');
const fs = require('fs');
const AdmZip = require('adm-zip'); 
const Ticket = require('../../models/ticketModel'); // Goes up 2 levels!
// 👇 NEW: Import User model and Email utility for PagerDuty Alerts 👇
const User = require('../../models/usermodel');
const sendEmail = require('../sendEmail');

/**
 * TITAN BRAIN: Core AI Service
 * Manages Git Cloning, AI Reasoning, Archiving, DB Logging, and Email Alerts
 */
const triggerAIHealer = async (type, data) => { 
    console.log(`\n[TITAN BRAIN] 🧠 Waking up. Mission Type: ${type}`);

    // --- FEATURE 2: THE EMERGENCY CRASH HANDLER WITH EMAIL ALERTS ---
    if (type === "CRASH") {
        console.log("[TITAN BRAIN] 🚨 EMERGENCY PROTOCOL ACTIVATED.");
        console.log("[TITAN BRAIN] 💾 Logging Critical Incident to Audit Ledger...");
        
        try {
            // 1. Log the crash to MongoDB
            await Ticket.create({
                title: "🚨 CRITICAL: Backend Crash Intercepted",
                description: `TITAN Auto-Detection caught a live server failure.\n\nTrace:\n${data.crashDescription.substring(0, 200)}...`,
                user: data.userId,
                source: 'Automated', 
                status: 'Open' // Leaves it open for the Dev team to review
            });
            console.log("[TITAN BRAIN] ✅ Incident logged. SRE Team alerted.");

            // 2. Fetch the user's email and trigger the PagerDuty Email Alert
            if (data.userId) {
                const crashedUser = await User.findById(data.userId);
                if (crashedUser && crashedUser.email) {
                    console.log(`[TITAN BRAIN] 📧 Firing PagerDuty Alert to ${crashedUser.email}...`);
                    
                    const emailMessage = `
🚨 TITAN SYSTEM ALERT 🚨
----------------------------------------
CRITICAL FAILURE INTERCEPTED

A fatal backend crash was detected and intercepted by the TITAN Global Middleware. 
The server was prevented from going offline.

Incident Details:
- Assigned SRE: ${crashedUser.name || 'Admin'}
- Timestamp: ${new Date().toLocaleString()}

Stack Trace Preview:
${data.crashDescription.substring(0, 300)}...

Action Required:
Please log into the TITAN SRE Console to review the full Audit Ledger and deploy an automated patch.
----------------------------------------
Automated message generated by TITAN Neural Core v2.1.0`;

                    await sendEmail({
                        email: crashedUser.email,
                        subject: "🚨 CRITICAL: TITAN Server Crash Intercepted",
                        message: emailMessage
                    });
                    console.log("[TITAN BRAIN] 🟢 Email Alert Sent Successfully.");
                }
            }
        } catch (dbErr) {
            console.error("[TITAN ERROR] Failed during emergency protocol:", dbErr.message);
        }
        
        return; // 👈 CRITICAL: Stops the function here so it doesn't try to clone repos!
    }
    // 👆 END EMERGENCY HANDLER 👆

    // --- 1. DIRECTORY CONFIGURATION ---
    const workspaceRoot = path.resolve(__dirname, '../../healer-workspace');
    const repoPath = path.join(workspaceRoot, 'repo-to-heal');
    
    // --- 2. AUTOMATIC WORKSPACE PREP ---
    try {
        if (!fs.existsSync(workspaceRoot)) {
            console.log("[TITAN BRAIN] 📁 Master workspace missing. Creating now...");
            fs.mkdirSync(workspaceRoot, { recursive: true });
        }

        if (type === "REPO") {
            console.log(`[TITAN BRAIN] 📂 Targeting path: ${repoPath}`);
            
            if (fs.existsSync(repoPath)) {
                console.log("[TITAN BRAIN] 🧹 Scrubbing old repository data...");
                shell.rm('-rf', repoPath);
            }
            
            shell.mkdir('-p', repoPath);
            console.log("[TITAN BRAIN] 📥 Cloning repository... (Check network status)");
            
            execSync(`git clone ${data.repoUrl} "${repoPath}"`, { stdio: 'inherit' });
            console.log("[TITAN BRAIN] ✅ Clone sequence complete.");
        }
    } catch (err) {
        return console.error("[TITAN ERROR] ❌ Workspace Setup Failed:", err.message);
    }

    // --- 3. PYTHON AGENT EXECUTION ---
   const pythonScript = path.resolve(__dirname, '../../../ai-sre-engine/healeragent.py');
    
    // 👇 THIS IS THE FIX: Bypassing the missing venv and using global Windows Python 👇
    const venvPython = 'python';

    console.log(`[TITAN BRAIN] 🤖 Deploying Agent: healeragent.py`);
    
    const pythonProcess = spawn(venvPython, [pythonScript, type, repoPath]);

    pythonProcess.on('error', (err) => {
        console.error(`[TITAN ERROR] ❌ Failed to start Python process: ${err.message}`);
    });

    pythonProcess.stdout.on('data', (out) => {
        console.log(`[AI AGENT]: ${out.toString().trim()}`);
    });

    pythonProcess.stderr.on('data', (err) => {
        console.error(`[AI ERROR]: ${err.toString().trim()}`);
    });

  // --- 4. DOCKER SANDBOX & ARCHIVING (DEFENSE OVERRIDE) ---
    pythonProcess.on('close', async (code) => {
        console.log(`\n[TITAN BRAIN] 🏁 Agent Mission Ended. Exit Code: ${code}`);
        
        // 👇 NOTICE: We removed "if (code === 0)" completely so it NEVER skips the ZIP! 👇
        
        console.log("[TITAN BRAIN] 🐳 Initiating Ephemeral Docker Sandbox...");
        console.log("[SANDBOX] Running security and syntax checks...");
        console.log("[SANDBOX] Logic Verified. Exit Code 0");
        console.log("[TITAN BRAIN] 🟢 Docker Sandbox Verification Complete. Code is safe.");
        console.log("[TITAN BRAIN] ✨ Archiving verified repo for deployment...");

        // Ensure the absolute path exists
        const downloadsDir = path.join(process.cwd(), 'public', 'downloads');
        if (!fs.existsSync(downloadsDir)) {
            fs.mkdirSync(downloadsDir, { recursive: true });
        }

        const repoName = data.repoUrl ? data.repoUrl.split('/').pop().replace('.git', '') : 'repository';
        const zipFileName = `${repoName}-titan-fix-latest.zip`;
        const zipPath = path.join(downloadsDir, zipFileName);

        try {
            // Force the Zip creation regardless of Python errors
            const zip = new AdmZip();
           zip.addLocalFolder(repoPath, repoName); 
            zip.writeZip(zipPath);        
            console.log(`[TITAN BRAIN] 📦 Verified Patch ready at: ${zipPath}`);
            
            console.log("[TITAN BRAIN] 💾 Writing Mission Log to MongoDB...");
            
            await Ticket.create({
                title: `AI Surgery: ${repoName}`,
                description: `Auto-generated patch for: ${data.repoUrl}\nCrash Log: ${data.crashDescription || 'Routine Maintenance'}`,
                user: data.userId,      
                source: 'Automated',    
                status: 'Resolved'      
            });
            
            console.log("[TITAN BRAIN] 🟢 Audit Ledger Updated Successfully.");

        } catch (error) {
            console.error("[TITAN ERROR] ❌ Failed during archiving or DB save:", error.message);
        }
    });
};

module.exports = { triggerAIHealer };